version: '3.4'

networks:
  synccookies-prod:
    driver: bridge

services:
  synccookies.api:
    container_name: api_prod
    image: ${DOCKER_REGISTRY-}synccookiesapi:1.0
    ports:
      - "5000:80"
    environment:
      DB_CONNECTION_STRING: "User ID=testuser; Password=123; Server=db; Port=5432; Database=SyncCookiesTest;"
    networks:
      - synccookies-prod

  db:
    container_name: db_prod
    environment:
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "SyncCookieTest"
    volumes:
      - "./postgres/prod/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - synccookies-prod

  proxy:
    container_name: proxy_prod
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - synccookies-prod    