version: '3.4'

networks:
  synccookies-test:
    driver: bridge

services:
  synccookies.api:
    # container_name: api
    image: ${DOCKER_REGISTRY-}synccookiesapi
    ports:
      - "8082:80"
    environment:
      DB_CONNECTION_STRING: "User ID=testuser; Password=123; Server=db; Port=5432; Database=SyncCookiesTest;"
    networks:
      - synccookies-test

  db:
    # container_name: db
    environment:
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "SyncCookiesTest"
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    ports:
      - "8081:5432"
    networks:
      - synccookies-test

  # proxy:
  #   container_name: proxy
  #   volumes:
  #     - ./nginx.test.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - synccookies-test    