version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge

services:
  synccookies.api:
    container_name: api
    image: ${DOCKER_REGISTRY-}synccookiesapi
    build:
      context: .
      dockerfile: SyncCookies.Api/Dockerfile
    ports:
      - "5000:80"
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_CONNECTION_STRING: "User ID=testuser; Password=123; Server=db; Port=5432; Database=SyncCookieTest;"
    command: ["dotnet", "ef", "database update"]
    networks:
      - dockerapi-dev

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "SyncCookieTest"
    volumes:
      - "./postgres/data:/var/lib/postgres/data"
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - dockerapi-dev